name: Deploy frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{secrets.DOCKER_NAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - run: docker build -t evrad7/docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true --name docker-react evrad7/docker-react npm run test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: deplay to Elastic beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Docker-react
          environment_name: Docker-react-env
          version_label: ${{ github.sha }}
          # existing_bucket_name: elasticbeanstalk-eu-west-3-767397743973
          region: eu-west-3
          deployment_package: deploy.zip